config/routes.rb
Rails.application.routes.draw do
  # URLs are carefully designed, resource helpers don't suit.

  get "gems", to: "projects#index", as: :projects
  get "search", to: "projects#search", as: :search_projects

  get "gems/:id", to: "versions#show", as: :version, constraints: {id: Patterns::NONGREEDY_SLUG, format: /html|json|gem|gemspec|yaml/}
  get "gems/:id/other", to: "versions#other", as: :other_version, constraints: {id: Patterns::NONGREEDY_SLUG}

  get "gems/:version_id/browse(/*path)", to: "packages#browse", as: :browse_version, constraints: {version_id: Patterns::NONGREEDY_SLUG, path: /.+/}
  get "gems/:version_id/raw(/*path)", to: "packages#raw", as: :raw_version, constraints: {version_id: Patterns::NONGREEDY_SLUG, path: /.+/}

  root to: "home#show"
end

app/models/package.rb
require "rubygems/package"

class Package
  include ActiveModel::Model

  class NotFound < RuntimeError; end
  class PackageNotFound < NotFound; end
  class MetadataNotFound < NotFound; end
  class DataNotFound < NotFound; end
  class FileNotFound < NotFound; end

  def initialize(path)
    raise PackageNotFound, "doesn't exist: #{path.inspect}" unless File.exists? path

    @path = path
  end

  attr_reader :path

  def basename
    @basename ||= File.basename(path)
  end

  def full_name
    @full_name ||= File.basename(path, ".gem")
  end

  def specification
    metadata
  end

  def tar_file &block
    File.open path, &block
  end

  def tar &block
    tar_file do |file|
      Gem::Package::TarReader.new file, &block
    end
  end

  def metadata_file &block
    tar do |tar|
      tar.each do |entry|
        return gzipped_file entry, &block if entry.full_name == "metadata.gz"
        return yield entry if entry.full_name == "metadata"
      end
    end
    raise MetadataNotFound
  end

  def metadata_yaml
    @metadata_yaml ||= Rails.cache.fetch "GemFile/#{path}/metadata_yaml" do
      metadata_file do |metadata_file|
        metadata_file.read
      end
    end
  end

  def metadata
    @metadata ||= Gem::Specification.from_yaml metadata_yaml
  end

  def metadata_ruby
    specification.to_ruby
  end

  def data_tar_file &block
    tar do |tar|
      tar.each do |entry|
        return gzipped_file entry, &block if entry.full_name == "data.tar.gz"
        return block.call(entry) if entry.full_name == "data.tar"
      end
    end
    raise DataNotFound
  end

  def data_tar &block
    data_tar_file do |data_tar_file|
      Gem::Package::TarReader.new data_tar_file, &block
    end
  end

  def data_file path, &block
    data_tar do |data_tar|
      data_tar.each do |entry|
        if entry.full_name == path
          return yield entry
        end
      end
    end
    raise FileNotFound
  end

  def headers
    @headers ||= Rails.cache.fetch "Package/#{full_name}/headers" do
      {}.tap do |hash|
        data_tar do |data_tar|
          data_tar.each do |entry|
            hash[entry.full_name] = entry.header
          end
        end
      end.freeze
    end
  end

  def paths
    @paths ||= headers.keys
  end

  def tree
    @tree ||= Rails.cache.fetch "Package/#{full_name}/tree" do
      {}.tap do |hash|
        headers.each do |path, header|
          components = path.split('/')
          components[0...-1].inject(hash) { |hash, component| hash[component] ||= {} }[components.last] = header
        end
      end.freeze
    end
  end

  alias to_hash tree

  def [](path)
    path.split('/').compact.inject(tree) { |paths, component| paths[component] }
  end

  def glob(pattern, flags=0)
    paths.select { |path| File.fnmatch(pattern, path, flags) }
  end

  def readme
    glob("README*", File::FNM_CASEFOLD).sort_by(&:length).first
  end

protected

  def gzipped_file file, &block
    begin
      gz = Zlib::GzipReader.new file
      yield gz
    ensure
      gz.close if gz
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, format: {with: Patterns::NAME}

  has_many :versions, dependent: :destroy

  def latest_version
    versions.last
  end

  def to_s
    name
  end
end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :project
  has_many :other_versions, through: :project, source: :versions

  validates :number, format: {with: Patterns::VERSION}
  validates :platform, format: {with: Patterns::PLATFORM}
  validates :full_name, uniqueness: true

  before_save :cache_full_name

  delegate :name, to: :project

  def version
    number
  end

  def platform
    super || Gem::Platform::RUBY
  end

  def platform?
    platform != Gem::Platform::RUBY
  end

  def full_name
    if platform?
      "#{name}-#{version}-#{platform}"
    else
      "#{name}-#{version}"
    end
  end

  def to_s
    full_name
  end

  def to_param
    full_name
  end

  def package_path
    Rails.root.join("public", "gems", "#{full_name}.gem")
  end

  def package
    @package ||= Package.new(package_path)
  end

  def specification
    package.specification
  end

private

  def cache_full_name
    self.full_name = full_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :prepare_version
  before_action :prepare_package

  def browse
    @entry = @package[path_param]
  end

  def raw
    @package.data_file(path_param) do |file|
      send_data file.data, filename: file.name, type: file.content_type, disposition: file.disposition
    end
  end

private

  def version_param
    params.require(:version_id)
  end

  def path_param
    request.path_parameters[:path].to_s.tap { |path| Rails.logger.info "path: #{path.inspect}" }
  end

  helper_method :version_param, :path_param

  def prepare_version
    @version = Version.find_by_full_name!(version_param)
  end

  def prepare_package
    @package = @version.package
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :prepare_projects

  def index
    @projects = @projects.page(page_param)
  end

  def search
    @projects = @projects.fuzzy_search(query_param).page(page_param)
  end

private

  helper_method def page_param
    @page_param ||= params[:page]
  end

  helper_method def query_param
    @query_param ||= params.require(:q)
  end

  def prepare_projects
    @projects = Project.all
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :redirect_bare_project, only: [:show]
  before_action :prepare_version

  def show
    respond_to do |format|
      format.html
      format.json { render json: @version }
      format.gem { send_file @version.package_path }
      format.gemspec { send_data @version.package.metadata_ruby, disposition: :inline }
      format.yaml { send_data @version.package.metadata_yaml }
    end
  end

  def other
    respond_to do |format|
      format.html
      format.json { render json: @version.other_versions }
    end
  end

private

  def redirect_bare_project
    if project = Project.find_by_name(params[:id])
      redirect_to project.latest_version
    end
  end

  def version_param
    params.require(:id)
  end

  def prepare_version
    @version = Version.find_by_full_name!(version_param)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller_action
    "#{controller_name}##{action_name}"
  end
end

app/helpers/packages_helper.rb
module PackagesHelper
  def subpaths_to path, &block
    path.split('/').reject(&:blank?).inject("") do |path, component|
      path << "/" unless path.blank?
      path << component
      yield component, path
      path
    end
  end
end

app/helpers/versions_helper.rb
module VersionsHelper
  def subpaths_to path, &block
    path.split('/').reject(&:blank?).inject("") do |path, component|
      path << "/" unless path.blank?
      path << component
      yield component, path
      path
    end
  end

  def render_markup(name, data)
    tag(:span, class: "glyphicon glyphicon-link")
    raw GitHub::Markup.render(name, data)
  end
end

app/views/home/show.html.slim
section.page
  h2 What can I do?

  p Search for a gem above, or just go ahead and browse, and you can check out dependencies, versions available, browse inside the gem's files just like GitHub, and view documentation just like RubyDoc.info.

  h2 Using this as a gem source

  p This is also a gem hosting service for rubygems and bundler. To install a gem from here:

  = raw Pygments.highlight(%{gem install --clear-sources --source #{root_url.inspect} GEM}, lexer: :sh).sub("GEM", "<em>GEM</em>")

  p Or tell bundler to use this as a mirror:

  = raw Pygments.highlight(%{bundle config --global mirror.https://rubygems.org #{root_url.inspect}}, lexer: :sh)

  p Or add this as the source in your Gemfile:

  = raw Pygments.highlight(%{source #{root_url.inspect}}, lexer: :ruby)

app/views/layouts/application.html.slim
doctype
html
  head
    title Rubygems Mirror
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags
  body
    header.page
      h1 Rubygems Mirror

      nav
        ul
          li class=("active" if controller_name == "home") = link_to "Home", root_path
          li class=("active" if controller_name.in? "projects") = link_to "Gems", projects_path
          li = form_tag search_projects_path, method: :get, class: "form-inline" do
            = search_field_tag :q, (query_param if controller_action == "projects#search"), placeholder: "Search...", class: "form-control"


    = yield

    footer.page
      p Made for #{link_to "Railscamp 15", "http://bne15.railscamps.org"} by #{link_to "@sj26", "http://sj26.com"}

    = javascript_include_tag "application"

app/views/projects/index.html.slim
section.page
  h2 Projects

  ul
    - @projects.each do |project|
      li
        => link_to project, project.latest_version
        | (#{project.latest_version.number})

  = paginate @projects

app/views/projects/search.html.slim
section.page.search
  h2 Results for &ldquo;#{query_param}&rdquo;

  ul
    - @projects.each do |project|
      li
        = link_to project, version_path(project.latest_version)
        span.text-muted
          |  (#{project.latest_version.number})

  = paginate @projects

app/views/versions/_browse_directory.html.slim
section.page.directory
  table.directory.table.table-striped
    thead
      tr
        th.name Name
        th.size Size
    tbody
      - directory.each do |name, entry|
        tr
          td.name
            = link_to name, browse_version_path(version, File.join(*[path.presence, name].compact))
            =< content_tag :span, "/", class: "text-muted" if entry.is_a? Hash
          td.size = number_to_human_size entry.size if entry.respond_to? :size

app/views/versions/_browse_file.html.slim
section.page
  article.content.clearfix class=file.language.try(:default_alias_name)
    - if GitHub::Markup.can_render? file.header.name
      .markup
        = render_markup file.header.name, file.read

    - elsif file.image?
      .image
        = image_tag raw_version_path(version, path)

    - elsif file.safe_to_colorize?
      .colorized
        = raw file.colorize options: {linenos: "table", lineanchors: "L", anchorlinenos: true}

    - elsif file.viewable?
      .raw
        pre = file.data

    - else
      .binary
        p Sorry, this file is a bit too much to handle. You can #{link_to "download it", raw_version_path(version, path)}.

app/views/versions/_header.html.slim
section.page.version-header
  .clearfix
    h2.pull-left
      => @version.name
      small
        | (
        = @version.number
        - if @version.platform?
          =< @version.platform
        | )
    nav.btn-group.pull-right
      = link_to "Download", version_path(@version, format: "gem"), class: "btn btn-default"
      = link_to "Specification", version_path(@version, format: "gemspec"), class: "btn btn-default"

  p = @version.summary

section.page.version-tabs
  nav
    ul.nav.nav-tabs
      li class=("active" if controller_action == "versions#show")
        = link_to "Information", version_path(@version)
      li class=("active" if controller_action == "versions#other")
        = link_to "Versions", other_version_path(@version)
      li class=("active" if controller_action == "packages#browse")
        = link_to "Browse", browse_version_path(@version)

app/views/versions/browse.html.slim
= render "header"
= render "tabs"

section.page.breadcumby
  ul.breadcrumb.pull-left
    li = link_to "Root", browse_version_path(@version)
    - subpaths_to @path do |component, subpath|
      - if not current_page? browse_version_path(@version, subpath.presence)
        li = link_to_unless_current component, browse_version_path(@version, subpath.presence)
      - else
        li.active = component

  - unless @entry.is_a? Hash
    nav.btn-group.btn-group-sm.pull-right
      = link_to "Raw", raw_version_path(@version, @path), class: "btn btn-default"

- if @entry.is_a? Hash
  = render "browse_directory", version: @version, path: @path, directory: @entry

  - if @path.blank? and @package.readme
    - @package.data_file(@package.readme) do |file|
      #readme
        section.page
          h3 = file.header.name

        = render "browse_file", version: @version, path: @path, file: file

- else
  - @package.data_file(@path) do |file|
    = render "browse_file", version: @version, path: @path, file: file

app/views/versions/other.html.slim
= render "versions/header"

section.page
  ul
    - @version.project.versions.each do |version|
      li = link_to version, version

app/views/versions/show.html.slim
= render "versions/header"

section.page
  - if @version.description
    - # simple_format does too much
    .description
      = safe_join(@version.description.split(/\n{2,}/).map { |text| content_tag :p, text })

  h2 Bundler

  = raw Pygments.highlight(%{gem #{@version.name.inspect}, #{@version.specification.version.approximate_recommendation.inspect}}, lexer: :ruby)

  h2 Information

  dl.dl-horizontal
    dt Homepage
    dd= link_to @version.specification.homepage, @version.specification.homepage

    dt Email
    dd= Array.wrap(@version.specification.email).map { |email| mail_to email }.to_sentence.html_safe

    dt Date
    dd= time_tag @version.specification.date

  .row
    - if @version.specification.dependencies.present?
      .col-sm-6
        h2 Dependencies
        ul.versions
          - @version.specification.dependencies.each do |dependency|
            li.version
              = link_to dependency.name, version_path(dependency.name)
              = dependency.requirement

    - if @version.specification.development_dependencies.present?
      .col-sm-6
        h2 Dev Dependencies
        ul.versions
        - @version.specification.development_dependencies.each do |dependency|
          li.version
            = link_to dependency.name, version_path(dependency.name)
            = dependency.requirement